# Generated by Django 5.2.2 on 2026-03-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imported_from_json',
            field=models.BooleanField(default=False),
        ),
    ]
