# Generated by Django 5.2.2 on 2026-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
