# Generated by Django 5.2.2 on 2026-02-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_career_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='career',
            name='demand_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='career',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Moderate'), (4, 'Hard'), (5, 'Very Hard')], default=3),
        ),
        migrations.AddField(
            model_name='career',
            name='min_education',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('graduate', 'Graduate'), ('postgraduate', 'Post Graduate')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(blank=True, choices=[('arts', 'Arts'), ('commerce', 'Commerce'), ('medical', 'Medical'), ('non-medical', 'Non Medical'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='accounts.studentprofile')),
            ],
        ),
    ]
