# Generated by Django 5.2.2 on 2026-02-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_skills_career_demand_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='post_graduation_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
