# Generated by Django 5.2.2 on 2026-02-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_post_graduation_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerquizresult',
            name='suggested_career',
        ),
        migrations.RemoveField(
            model_name='careerquizresult',
            name='total_score',
        ),
        migrations.AddField(
            model_name='careerquizresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='careerquizoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.careerquizquestion'),
        ),
        migrations.CreateModel(
            name='CombinedCareerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.IntegerField(default=0)),
                ('quiz_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
                ('suggested_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.career')),
            ],
        ),
    ]
