# Generated by Django 5.2.2 on 2026-02-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='personality_quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
