# Generated by Django 5.2.2 on 2026-02-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile_personality_quiz_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedcareerresult',
            name='match_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combinedcareerresult',
            name='skill_gap',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
