# Generated by Django 5.2.2 on 2026-03-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_combinedcareerresult_match_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='imported_from_json',
            field=models.BooleanField(default=False),
        ),
    ]
