# Generated by Django 5.2.2 on 2026-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_career_imported_from_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
