# Generated by Django 5.2.2 on 2026-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_map_old_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedcareerresult',
            name='category_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
